### ISSUE TITLE
Week 11: v1.3 Milestone

### ISSUE THREAD

**Issue by geezlouisee** [CS2103-AY1819S2-W17-3/main#105]
- [ ] Each of us to continue working on the features we want to implement
- [ ] v1.3 jar file released on GitHub
- [ ] v1.3 milestone properly wrapped up on GitHub

**v1.3 Documentation**
- [ ] AboutUs page: Update to reflect current state of roles and responsibilities.
- [ ] User Guide: Update based on the changes we made
- [ ] Developer Guide: Each of our section should be at least 3 pages

**Comment by Jackimaru96** [comment]
# v1.3 Milestone checklist! 
**Please check in the relevant sections so that I can properly wrap up the milestone!
### Updated UI in `README.adoc`
- [ ]

### jar file released
- [ ] 

### Mark here if you have implemented your feature
- [ ] @eugeneyl 
- [ ] @geezlouisee 
- [ ] @kjiaxuan 
- [ ] @JeremyLoye
- [ ] @Jackimaru96 

### Mark here if you have updated user guide on your feature
- [ ] @eugeneyl 
- [ ] @geezlouisee 
- [ ] @kjiaxuan 
- [ ] @JeremyLoye 
- [ ] @Jackimaru96 

### Code is RepoSense-compatible; go check [here](https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#search=&sort=displayName&since=2019-02-10&until=2019-03-26&timeframe=day&reverse=false&repoSort=true)

- [ ] @eugeneyl 
- [ ] @geezlouisee 
- [ ] @kjiaxuan 
- [ ] @JeremyLoye 
- [x] @Jackimaru96 

### Mark here if you have updated user guide on your feature
- [ ] @eugeneyl 
- [ ] @geezlouisee 
- [ ] @kjiaxuan 
- [ ] @JeremyLoye 
- [ ] @Jackimaru96 

### Mark here if you have updated developer guide (Not graded this milestone; but feedback)
- [ ] @eugeneyl 
- [ ] @geezlouisee 
- [ ] @kjiaxuan 
- [ ] @JeremyLoye 
- [ ] @Jackimaru96
