### ISSUE TITLE
v1.4 milestone implementations

### ISSUE THREAD

**Issue by Jackimaru96** [CS2103-AY1819S2-W17-3/main#135]
- [x] fix `CategoryBudget` logic - if new allocated budget is less than the current spending in the category, do not allow user to change that
- [x] `show` command to show the Category Budgets
- [x] implement UI to show total Budget as a bar with `currentSpendings`/`totalBudget`
- [x] UG updated with `show`, `theme`, `allocate` commands 
- [x] UG updated with GUI Introduction
- [x] Updated DG with `theme` and `show`
- [x] Finish up PPP with regards to CS2101 Checklist
- [x] Tests for implemented features
