### ISSUE TITLE
Week 12: mid v1.4 Milestone 

### ISSUE THREAD

**Issue by geezlouisee** [CS2103-AY1819S2-W17-3/main#179]
- [x] - Ensure features are more or less done 
- [x]     - (mock product demo during Wednesday's tutorial --> have to cover all features) 
- [x] - Consider increasing code coverage
- [x] - Consider tweaking product based on peer feedback
- [x] - Update UG and DG to match the product
- [x] - Create the first version of your Project Portfolio Page (PPP)
