### ISSUE TITLE
v1.4 Milestone Final Tasks and Implementations (self)

### ISSUE THREAD

**Issue by JeremyLoye** [CS2103-AY1819S2-W17-3/main#203]
- [x] Allow SetCommand to set budget multiple times
- [x] Add undo/redo support for SetFileCommand
- [x] Update undo/redo support for spending/editing/deleting to update `CategoryBudget` data in json data file
- [x] Fix bugs in EditCommand logic that cause it not to account changes to `CategoryBudget`
- [x] Fix bug of CategoryBudget not being updated if expense is recorded before allocation of CategoryBudget
- [x] Add test cases for `SetFile` and `Budget` features
- [x] Test app boundary values for bugs
- Changed Amount to only accept positive numbers
- Changed filename to be limited to only 250 Characters
- [x] Update User Guide, PPP and Developer Guide to reflect changes
