### ISSUE TITLE
Todo by v1.4 milestone (self-assign)

### ISSUE THREAD

**Issue by geezlouisee** [CS2103-AY1819S2-W17-3/main#213]
- [x] Add in more colours for summary pie chart (#214)
- [x] Remove unused code (especially those added in initially for d3.js Aster Plot implementation)
- [x] Update UG and DG (according to current implementation with pie chart)
- [x] Update PPP, UG and DG according to cs2101 rubrics

**Comment by geezlouisee** [comment]
#208 
- Removed some unused code (files related to Aster Plot implementation) 
- KIV: UG - whether to add Aster Plot implementation under `Upcoming Features`

**Comment by geezlouisee** [comment]
> #208
> 
> * Removed some unused code (files related to Aster Plot implementation)
> * KIV: UG - whether to add Aster Plot implementation under `Upcoming Features`

- Addressed both points in #242 and #235 respectively
