### ISSUE TITLE
Week 8: mid v1.2 Milestone

### ISSUE THREAD

**Issue by Jackimaru96** [CS2103-AY1819S2-W17-3/main#50]
# Code enhancements for Week 8 

### Refactoring
- [x] Remove Contact, Address, Email fields @JeremyLoye 
- [x] Rename tags to Category @geezlouisee 
- [x] Rename Person to Entry @eugeneyl 
- [x] Create allocate/increase command @Jackimaru96 
- [x] Renaming directories @kjiaxuan
