### ISSUE TITLE
Week 10: mid v1.3 Milestone

### ISSUE THREAD

**Issue by geezlouisee** [CS2103-AY1819S2-W17-3/main#89]
- [x] Update User Guide (address points mentioned in #88 )
- [x] Ensure Code is RepoSense-Compatible
- [x] Each of us to continue working on the features we want to implement 
    - #67 @eugeneyl 
    - #81 @geezlouisee 
    - #82 @Jackimaru96 
    - #85 @kjiaxuan 
    - #86 @JeremyLoye 
- [x] Update Developer Guide (each of our section should be at least **3 pages** by v1.3)
- [x] Try doing a proper product release

**Comment by geezlouisee** [comment]
- Already ensured our code is RepoSense-Compatible before milestone v1.2.
- #70 Fixed duplicate name problem in [Project Code Dashboard](https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#search=&sort=displayName&since=2019-02-10&until=2019-03-19&timeframe=day&reverse=false&repoSort=true)
